// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Parrainage.Infrastructure.Persistence;

#nullable disable

namespace Parrainage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ParrainageDbContext))]
    [Migration("20260706120000_AddReferralCandidateEmployeeId")]
    partial class AddReferralCandidateEmployeeId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is defined in ParrainageDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
