// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimeBackend.Data;

#nullable disable

namespace PrimeBackend.Data.Migrations
{
    [DbContext(typeof(PrimeDbContext))]
    [Migration("20260511000332_CelluleIndicatorPonderationPrimeChallenge")]
    partial class CelluleIndicatorPonderationPrimeChallenge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrimeBackend.Data.CelluleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PoleId");

                    b.ToTable("prime_cellule", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.CellulePrimeIndicatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CelluleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal?>("PonderationPct")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal?>("PonderationChallengePct")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal?>("PonderationPrimePct")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateStableId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CelluleId");

                    b.HasIndex("CelluleId", "SortOrder");

                    b.ToTable("prime_cellule_prime_indicator", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.DepartmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("prime_department", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.EmployeeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("CelluleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("PoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CelluleId");

                    b.HasIndex("PoleId");

                    b.HasIndex("TeamId");

                    b.ToTable("prime_employee", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.EmployeePrimeCellFicheEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CellSaisieJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CelluleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FillingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PoleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PolePrimeDraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupervisorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PolePrimeDraftId");

                    b.HasIndex("CelluleId", "Period");

                    b.HasIndex("EmployeeId", "Period")
                        .IsUnique();

                    b.HasIndex("SupervisorUserId", "Period");

                    b.ToTable("prime_employee_prime_cell_fiche", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.PoleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("prime_pole", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.SupervisorPolePrimeDraftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComputedJson")
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PoleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PoleSaisieJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SupervisorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TemplateDisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TemplateFormatVersion")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorUserId", "Period");

                    b.HasIndex("SupervisorUserId", "PoleId", "Period", "TemplateId")
                        .IsUnique();

                    b.ToTable("prime_supervisor_pole_prime_draft", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.SupervisorPrimeFicheEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComputedJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PoleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SaisieJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SupervisorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TemplateDisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TemplateFormatVersion")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorUserId", "Period");

                    b.ToTable("prime_supervisor_fiche", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.TeamEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CelluleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CelluleId");

                    b.ToTable("prime_team", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.CelluleEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.PoleEntity", "Pole")
                        .WithMany("Cells")
                        .HasForeignKey("PoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pole");
                });

            modelBuilder.Entity("PrimeBackend.Data.CellulePrimeIndicatorEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.CelluleEntity", "Cellule")
                        .WithMany("PrimeIndicators")
                        .HasForeignKey("CelluleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cellule");
                });

            modelBuilder.Entity("PrimeBackend.Data.EmployeeEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrimeBackend.Data.EmployeePrimeCellFicheEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.SupervisorPolePrimeDraftEntity", "PolePrimeDraft")
                        .WithMany("EmployeeFiches")
                        .HasForeignKey("PolePrimeDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolePrimeDraft");
                });

            modelBuilder.Entity("PrimeBackend.Data.PoleEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.DepartmentEntity", "Department")
                        .WithMany("Poles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PrimeBackend.Data.TeamEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.CelluleEntity", "Cellule")
                        .WithMany("Teams")
                        .HasForeignKey("CelluleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cellule");
                });

            modelBuilder.Entity("PrimeBackend.Data.CelluleEntity", b =>
                {
                    b.Navigation("PrimeIndicators");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PrimeBackend.Data.DepartmentEntity", b =>
                {
                    b.Navigation("Poles");
                });

            modelBuilder.Entity("PrimeBackend.Data.PoleEntity", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("PrimeBackend.Data.SupervisorPolePrimeDraftEntity", b =>
                {
                    b.Navigation("EmployeeFiches");
                });
#pragma warning restore 612, 618
        }
    }
}
