// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimeBackend.Data;

#nullable disable

namespace PrimeBackend.Data.Migrations
{
    [DbContext(typeof(PrimeDbContext))]
    [Migration("20260509135803_InitialPrimeOrg")]
    partial class InitialPrimeOrg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrimeBackend.Data.CelluleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PoleId");

                    b.ToTable("prime_cellule", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.DepartmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("prime_department", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.EmployeeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("CelluleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("PoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PoleId");

                    b.HasIndex("TeamId");

                    b.ToTable("prime_employee", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.PoleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("prime_pole", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.TeamEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CelluleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CelluleId");

                    b.ToTable("prime_team", (string)null);
                });

            modelBuilder.Entity("PrimeBackend.Data.CelluleEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.PoleEntity", "Pole")
                        .WithMany("Cells")
                        .HasForeignKey("PoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pole");
                });

            modelBuilder.Entity("PrimeBackend.Data.EmployeeEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrimeBackend.Data.PoleEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.DepartmentEntity", "Department")
                        .WithMany("Poles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PrimeBackend.Data.TeamEntity", b =>
                {
                    b.HasOne("PrimeBackend.Data.CelluleEntity", "Cellule")
                        .WithMany("Teams")
                        .HasForeignKey("CelluleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cellule");
                });

            modelBuilder.Entity("PrimeBackend.Data.CelluleEntity", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PrimeBackend.Data.DepartmentEntity", b =>
                {
                    b.Navigation("Poles");
                });

            modelBuilder.Entity("PrimeBackend.Data.PoleEntity", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
