// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PrimeBackend.Data;

#nullable disable

namespace PrimeBackend.Data.Migrations;

[DbContext(typeof(PrimeDbContext))]
[Migration("20260520120000_OrgOptionalAndDraftRootPole")]
partial class OrgOptionalAndDraftRootPole
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Le modèle cible est décrit dans PrimeDbContextModelSnapshot.
    }
}
