FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . ./
RUN npm run build -- --configuration production

FROM node:20-alpine AS runtime
WORKDIR /app

COPY --from=build /app/dist/auth-frontend ./dist/auth-frontend
COPY --from=build /app/node_modules ./node_modules

EXPOSE 4000

CMD ["node", "dist/auth-frontend/server/server.mjs"]