-- ===== BASE KYNTUS =====
CREATE USER kyntus_user WITH PASSWORD 'Kyntus@2026';
CREATE DATABASE kyntus_db OWNER kyntus_user;

\c kyntus_db

GRANT ALL ON SCHEMA public TO kyntus_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO kyntus_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO kyntus_user;

-- ===== BASE AUTH =====
CREATE USER auth_user WITH PASSWORD 'Auth@2026';
CREATE DATABASE auth_db OWNER auth_user;

\c auth_db

GRANT ALL ON SCHEMA public TO auth_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO auth_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO auth_user;

