// <auto-generated />
using System;
using Conge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Conge.Infrastructure.Migrations
{
    [DbContext(typeof(CongeDbContext))]
    [Migration("20260526110758_AddRoleToEmployeSnapshot")]
    partial class AddRoleToEmployeSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Conge.Domain.Entities.DemandeConge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommentaireManager")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDecision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motif")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("NombreJours")
                        .HasColumnType("double precision");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TypeConge")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TypeExceptionnel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("EmployeId", "Statut");

                    b.ToTable("demandes_conge", (string)null);
                });

            modelBuilder.Entity("Conge.Domain.Entities.EmployeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DerniereModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EmployeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstMineur")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceNom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("employe_snapshots", (string)null);
                });

            modelBuilder.Entity("Conge.Domain.Entities.SoldeConge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Annee")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DerniereModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeId")
                        .HasColumnType("uuid");

                    b.Property<double>("SoldeInitial")
                        .HasColumnType("double precision");

                    b.Property<double>("SoldeUtilise")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId", "Annee")
                        .IsUnique();

                    b.ToTable("soldes_conge", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
