server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location /qualite-app/ {
        try_files $uri $uri/ /qualite-app/index.html;
    }

    location = / {
        return 302 /qualite-app/;
    }
}
