// Generated by scripts/switch-kyntus-urls.ps1 - profile: local
window.__KYNTUS_PUBLIC_URLS__ = {
  host: 'localhost',
  gateway: 'http://localhost:8500',
  planningSpa: 'http://localhost:8200',
  authFrontend: 'http://localhost:8201',
  authLogin: 'http://localhost:8201/login',
  planningAuthCallback: 'http://localhost:8200/auth-callback'
};