param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('local', 'deploy')]
    [string]$Profile,

    [switch]$RecreateDocker
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

$source = switch ($Profile) {
    'local'  { Join-Path $root 'config\kyntus-public-urls.local.json' }
    'deploy' { Join-Path $root 'config\kyntus-public-urls.deploy.backup.json' }
}

if (-not (Test-Path $source)) {
    throw "Fichier profil introuvable: $source"
}

$urls = Get-Content -Raw -Path $source | ConvertFrom-Json
$activePath = Join-Path $root 'config\kyntus-public-urls.active.json'
Copy-Item -Path $source -Destination $activePath -Force

$runtimeJs = @"
// Generated by scripts/switch-kyntus-urls.ps1 - profile: $($urls.profile)
window.__KYNTUS_PUBLIC_URLS__ = {
  host: '$($urls.host)',
  gateway: '$($urls.gateway)',
  planningSpa: '$($urls.planningSpa)',
  authFrontend: '$($urls.authFrontend)',
  authLogin: '$($urls.authLogin)',
  planningAuthCallback: '$($urls.planningAuthCallback)'
};
"@

$runtimeTargets = @(
    (Join-Path $root 'config\kyntus-public-urls.runtime.js'),
    (Join-Path $root 'auth-frontend\public\kyntus-public-urls.js'),
    (Join-Path $root 'projet_kyntus_service_planning-frontend\public\kyntus-public-urls.js')
)

$utf8NoBom = New-Object System.Text.UTF8Encoding $false

function Update-TextFileLine {
    param(
        [string]$Path,
        [string]$Pattern,
        [string]$Replacement
    )
    if (-not (Test-Path $Path)) { return }
    $content = [System.IO.File]::ReadAllText($Path, $utf8NoBom)
    $updated = [regex]::Replace($content, $Pattern, $Replacement)
    [System.IO.File]::WriteAllText($Path, $updated, $utf8NoBom)
}

foreach ($target in $runtimeTargets) {
    $dir = Split-Path -Parent $target
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    [System.IO.File]::WriteAllText($target, $runtimeJs, $utf8NoBom)
}

$urlCacheBuster = "$($urls.profile)-$($urls.host)"
$indexHtmlTargets = @(
    (Join-Path $root 'auth-frontend\src\index.html'),
    (Join-Path $root 'projet_kyntus_service_planning-frontend\src\index.html')
)
foreach ($indexPath in $indexHtmlTargets) {
    if (-not (Test-Path $indexPath)) { continue }
    Update-TextFileLine -Path $indexPath `
        -Pattern 'kyntus-public-urls\.js\?v=[^"]+' `
        -Replacement "kyntus-public-urls.js?v=$urlCacheBuster"
    Update-TextFileLine -Path $indexPath `
        -Pattern 'kyntus-public-urls\.js"' `
        -Replacement "kyntus-public-urls.js?v=$urlCacheBuster`""
}

$ocelotPath = Join-Path $root 'init\ocelot.gateway.json'
Update-TextFileLine -Path $ocelotPath -Pattern '"BaseUrl":\s*"[^"]+"' -Replacement "`"BaseUrl`": `"$($urls.gateway)`""

$composePath = Join-Path $root 'docker-compose.yml'
Update-TextFileLine -Path $composePath -Pattern 'public_gateway_base:\s*"[^"]+"' -Replacement "public_gateway_base: `"$($urls.gateway)`""

$activeCheck = Get-Content -Raw -Path $activePath | ConvertFrom-Json
if ($activeCheck.profile -ne $urls.profile -or $activeCheck.host -ne $urls.host) {
    throw "Verification echouee: profil actif inattendu ($($activeCheck.profile) / $($activeCheck.host))"
}

Write-Output "Profil '$Profile' applique."
Write-Output "  gateway          -> $($urls.gateway)"
Write-Output "  planning SPA     -> $($urls.planningSpa)"
Write-Output "  auth login       -> $($urls.authLogin)"
Write-Output "  auth callback    -> $($urls.planningAuthCallback)"
Write-Output ""
Write-Output "Verification OK: config/kyntus-public-urls.active.json -> profile=$($activeCheck.profile), host=$($activeCheck.host)"
Write-Output "Runtime JS: config/kyntus-public-urls.runtime.js (monte dans Docker)"
Write-Output ""

if ($RecreateDocker) {
    Push-Location $root
    try {
        Write-Output "Recreation des conteneurs (montage du nouveau kyntus-public-urls.js)..."
        docker compose up -d --force-recreate api-gateway auth-frontend planning-frontend
        if ($LASTEXITCODE -ne 0) { throw "docker compose a echoue (code $LASTEXITCODE)" }
    }
    finally {
        Pop-Location
    }
    Write-Output "Conteneurs recrees."
}
else {
    Write-Output "Appliquer sans rebuild image:"
    Write-Output "  scripts\switch-kyntus-urls.cmd -Profile $Profile -RecreateDocker"
    Write-Output ""
    Write-Output "Si le navigateur redirige encore vers l'ancien host (10.10.10.25):"
    Write-Output "  Ctrl+Shift+R sur http://localhost:8200 et http://localhost:8201"
}
