<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RootNamespace>ParrainageBackend</RootNamespace>
    <DefaultItemExcludes>$(DefaultItemExcludes);ParrainageBackend.Tests/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ParrainageBackend.Tests" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="ParrainageBackend.Tests/**" />
    <Content Remove="ParrainageBackend.Tests/**" />
    <None Remove="ParrainageBackend.Tests/**" />
    <EmbeddedResource Remove="ParrainageBackend.Tests/**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kyntus.Iam\Kyntus.Iam.csproj" />
    <ProjectReference Include="..\Kyntus.Identity.Jwt\Kyntus.Identity.Jwt.csproj" />
    <ProjectReference Include="..\Messaging.Contracts\Messaging.Contracts.csproj" />
    <PackageReference Include="MassTransit" Version="8.3.6" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
</Project>
